### ISSUE TITLE
Forgotten copy & pasted comment

### ISSUE THREAD

**Issue by mudrd8mz** [streamingltd/MEDIAL-Moodle-Filter#1]
https://github.com/streamingltd/MEDIAL-Moodle-Filter/blob/fecb7a6f128d5ba7a82c22baf549a6d08c5c8bdf/lang/en/filter_medial.php#L18 seems to be a copy & paste relic.

**Comment by tim1mw** [comment]
Now fixed in the latest development version, will be pushed here once QA is complete.
