### ISSUE TITLE
Invalid Bug tracker URL in the plugins directory

### ISSUE THREAD

**Issue by mudrd8mz** [streamingltd/MEDIAL-Moodle-Filter#2]
The record https://moodle.org/plugins/filter_medial should be fixed so that the "Bug tracker URL" contains a real public transparent issue tracker such as this one https://github.com/streamingltd/MEDIAL-Moodle-Filter/issues

The current location https://support.medial.com/ does not seem to suit well this purpose.

**Comment by tim1mw** [comment]
We prefer our customers to contact us via our support URL, this is intentional.

**Comment by mudrd8mz** [comment]
I am sorry guys. This has been discussed internally in the Plugins guardians team and the conclusion is that a public issue tracker is a requirement for hosting plugins in the Moodle Plugins directory. It's not an optional preference but a mandatory part of the open source project culture. Please fix the record. Thank you for understanding and co-operation.

**Comment by tim1mw** [comment]
I'll feed that back to the person who manages the plugin directory listings (not me), I don't think that changing the URL will be a problem if it is a requirement.
